const FlightData = [
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  {
    id: 1,
    firstImg:
      "https://r-xx.bstatic.com/data/airlines_logo/6E.png",
    firstflight: "Indigo",
    firstSTime:"12:05 PM",
    firstETime:"1:10 PM",
    Fpnrno:"Jul 26",
    FHours:'1h 05m',

    secongImg:"https://r-xx.bstatic.com/data/airlines_logo/AI.png",
    secondflight: "Air India",
    secondSTime:"2:00 AM",
    secondETime:"04:00 PM",
    pnrno1:"Jul 26",
    SHours:'2h 05m',
    Spnrno:"Jul 28",
  },
  ];

export default FlightData;
